# vim:ft=zsh sw=2 ts=2 et:

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export path=(
  /usr/local/opt/postgresql@10/bin
  $path
)

alias vim='/usr/local/bin/nvim'
alias vi='/usr/local/bin/nvim'

hash -d mike="$HOME/Dropbox/mike"
alias mike='nocorrect ~mike'

hash -d desk="$HOME/Desktop"
alias desk='nocorrect ~desk'

hash -d desktop="$HOME/Desktop"
alias desktop='nocorrect ~desktop'

hash -d dropbox="$HOME/Dropbox/mike"
alias dropbox='nocorrect ~dropbox'

alias -g gi='| grep -i '
alias -g lx='l -10'
alias -g lxx='l -20'
alias -g lxxx='l -30'

alias b='bundle'
alias be='bundle exec'

alias bsl='brew service list'
alias gba='git branch --all'
alias gco='git checkout'
alias gfa='git fetch --all --prune'
alias gfp='git format-patch HEAD~1 --no-color --stdout'
alias gs='git status --short'
alias gss='git status --short'
alias gwd='git diff --word-diff'

alias ll='ls -alh'

alias cwd='pwd | pbcopy'

# alias git='/usr/local/bin/hub'

alias listening-on='lsof -Pni4 | grep LISTEN'

alias preview='open -a Preview'
alias acrobat='open -a Adobe\ Acrobat\ Reader\ DC'

alias -s gif=preview
alias -s jpeg=preview
alias -s jpg=preview
alias -s png=preview

alias -s pdf=acrobat

alias -s coffee=vim
alias -s conf=vim
alias -s css=vim
alias -s csv=vim
alias -s erb=vim
alias -s example=vim
alias -s haml=vim
alias -s html=vim
alias -s js=vim
alias -s json=vim
alias -s lock=vim
alias -s markdown=vim
alias -s md=vim
alias -s pid=vim
alias -s rake=vim
alias -s rb=vim
alias -s ru=vim
alias -s scss=vim
alias -s sql=vim
alias -s srt=vim
alias -s text=vim
alias -s txt=vim
alias -s vim=vim
alias -s xml=vim
alias -s yml=vim

function clear-scrollback-buffer {
  # function klear () { printf "\33c\e[3J" }

  # Behavior of clear:
  # 1. clear scrollback if E3 cap is supported (terminal, platform specific)
  # 2. then clear visible screen
  # For some terminal 'e[3J' need to be sent explicitly to clear scrollback
  clear && printf '\ec\e[3J'
  # .reset-prompt: bypass the zsh-syntax-highlighting wrapper
  # https://github.com/sorin-ionescu/prezto/issues/1026
  # https://github.com/zsh-users/zsh-autosuggestions/issues/107#issuecomment-183824034
  # -R: redisplay the prompt to avoid old prompts being eaten up
  # https://github.com/Powerlevel9k/powerlevel9k/pull/1176#discussion_r299303453
  zle && zle .reset-prompt && zle -R
}

zle -N clear-scrollback-buffer
bindkey '^L' clear-scrollback-buffer

alias klear='clear-scrollback-buffer'
alias clear\!='clear-scrollback-buffer'

source '/usr/local/opt/fzf/shell/completion.zsh'
source '/usr/local/opt/fzf/shell/key-bindings.zsh'

source ~/.asdf/asdf.sh
# append completions to fpath
fpath=(${ASDF_DIR}/completions $fpath)
# initialise completions with ZSH's compinit
autoload -Uz compinit
compinit

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
